# 端口号
server:
  port: 8084

--- #################### 数据库相关配置 ####################

spring:
  profiles:
    include: undertow  # 引用其他的yml文件
  # 数据源配置项
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/im-core?useSSL=false&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true # MySQL Connector/J 8.X 连接的示例
    username: root # 数据库账号
    password: 19940806 # 数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver
    # HikariCP 自定义配置，对应 HikariConfig 配置属性类
    hikari:
      minimum-idle: 10 # 池中维护的最小空闲连接数，默认为 10 个。
      maximum-pool-size: 10 # 池中最大连接数，包括闲置和使用中的连接，默认为 10 个。
  main:
    allow-bean-definition-overriding: true


# mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:/mapper/*.xml
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: false
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #打印sql
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl



# TODO: security
security:
  expiration: 30                                                      #JWT过期时间
  secret: 'dasfdffdsfgfadgfshfghfgdsfgxcxfdghhfh'                     #JWT盐值
  ignore-url:
    - '/user/login'
    - '/user/encrypt'
    - '/user/publickey'
    - '/user/password'
    - '/user/sms'
    - '/auth/captcha'
    - '/doc.html'
    - '/swagger-ui.html'
    - '/webjars/**'
    - '/swagger-resources/**'
    - '/v2/**'
    - '/v3/**'
  rsa:
    key:
      secret: '1234567890' #RSA加密盐值


# TODO: log settings
logging:
  config: classpath:logback-plus.xml  #日志配置文件，会在当前项目下去找日志配置文件
  level:
    org.springframework: warn

# TODO 榛子云短信服务
sms:
  apiUrl: https://sms_developer.zhenzikj.com
  appId: 112181
  appSecret: 86813b86-b431-46ea-bd55-fcf63c2990a3